version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${SPRING_DATASOURCE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  redis:
#    image: redis:latest
#    restart: always
#    environment:
#      REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
#    ports:
#      - "${SPRING_REDIS_PORT}:6379"

volumes:
  pgdata:
